// Curated data for ~30 Indian pharmaceutical manufacturers
// Sources: Public market data, FDA/WHO databases, annual reports

export interface ManufacturerSeed {
  name: string;
  slug: string;
  headquarters?: string;
  foundedYear?: number;
  marketCapBillion?: number; // USD billions
  globalRank?: number; // Revenue rank among Indian pharma
  usFdaApproved: boolean;
  whoPrequalified: boolean;
  eugmpCompliant: boolean;
  description?: string;
  websiteUrl?: string;
  // Alternate name patterns for fuzzy matching against Drug.manufacturer
  aliases: string[];
}

export const manufacturerSeedData: ManufacturerSeed[] = [
  // ─── PREMIUM TIER (85-100) ──────────────────────────────────
  {
    name: "Sun Pharmaceutical Industries",
    slug: "sun-pharma",
    headquarters: "Mumbai, India",
    foundedYear: 1983,
    marketCapBillion: 42.0,
    globalRank: 1,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "India's largest and the world's 4th largest generic pharmaceutical company by revenue.",
    websiteUrl: "https://www.sunpharma.com",
    aliases: ["Sun Pharma", "Sun Pharmaceutical", "Sun Pharma Laboratories", "Ranbaxy"],
  },
  {
    name: "Cipla Ltd",
    slug: "cipla",
    headquarters: "Mumbai, India",
    foundedYear: 1935,
    marketCapBillion: 13.5,
    globalRank: 3,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "Pioneer in affordable medicines, known for making HIV/AIDS drugs accessible globally.",
    websiteUrl: "https://www.cipla.com",
    aliases: ["Cipla", "Cipla Ltd"],
  },
  {
    name: "Dr. Reddy's Laboratories",
    slug: "dr-reddys",
    headquarters: "Hyderabad, India",
    foundedYear: 1984,
    marketCapBillion: 12.0,
    globalRank: 4,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "Multinational pharmaceutical company with operations in over 100 countries.",
    websiteUrl: "https://www.drreddys.com",
    aliases: ["Dr. Reddy's", "Dr Reddy's", "Dr. Reddys", "DRL"],
  },
  {
    name: "Lupin Ltd",
    slug: "lupin",
    headquarters: "Mumbai, India",
    foundedYear: 1968,
    marketCapBillion: 9.5,
    globalRank: 5,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "Global leader in anti-TB drugs and a major player in cardiovascular, diabetology, and respiratory segments.",
    websiteUrl: "https://www.lupin.com",
    aliases: ["Lupin", "Lupin Ltd", "Lupin Limited"],
  },
  {
    name: "Zydus Lifesciences",
    slug: "zydus",
    headquarters: "Ahmedabad, India",
    foundedYear: 1952,
    marketCapBillion: 11.0,
    globalRank: 6,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "Innovation-driven pharma company known for developing India's first indigenously developed COVID-19 vaccine.",
    websiteUrl: "https://www.zyduslife.com",
    aliases: ["Zydus", "Zydus Cadila", "Cadila Healthcare", "Zydus Lifesciences"],
  },

  // ─── TRUSTED TIER (65-84) ──────────────────────────────────
  {
    name: "Torrent Pharmaceuticals",
    slug: "torrent-pharma",
    headquarters: "Ahmedabad, India",
    foundedYear: 1959,
    marketCapBillion: 6.5,
    globalRank: 8,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "Major Indian pharma company with strong presence in cardiovascular and CNS segments.",
    websiteUrl: "https://www.torrentpharma.com",
    aliases: ["Torrent", "Torrent Pharma", "Torrent Pharmaceuticals"],
  },
  {
    name: "Glenmark Pharmaceuticals",
    slug: "glenmark",
    headquarters: "Mumbai, India",
    foundedYear: 1977,
    marketCapBillion: 4.0,
    globalRank: 10,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "Innovation-led pharmaceutical company with a strong dermatology and respiratory portfolio.",
    websiteUrl: "https://www.glenmarkpharma.com",
    aliases: ["Glenmark", "Glenmark Pharma"],
  },
  {
    name: "Alkem Laboratories",
    slug: "alkem",
    headquarters: "Mumbai, India",
    foundedYear: 1973,
    marketCapBillion: 7.5,
    globalRank: 7,
    usFdaApproved: true,
    whoPrequalified: false,
    eugmpCompliant: false,
    description:
      "One of India's largest pharmaceutical companies with leadership in anti-infective and gastro segments.",
    websiteUrl: "https://www.alkemlabs.com",
    aliases: ["Alkem", "Alkem Labs", "Alkem Laboratories"],
  },
  {
    name: "Mankind Pharma",
    slug: "mankind",
    headquarters: "New Delhi, India",
    foundedYear: 1995,
    marketCapBillion: 8.0,
    globalRank: 9,
    usFdaApproved: false,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "India's fastest-growing pharma company focused on making quality healthcare affordable.",
    websiteUrl: "https://www.mankindpharma.com",
    aliases: ["Mankind", "Mankind Pharma"],
  },
  {
    name: "Intas Pharmaceuticals",
    slug: "intas",
    headquarters: "Ahmedabad, India",
    foundedYear: 1984,
    marketCapBillion: 3.5,
    globalRank: 12,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "Leading Indian pharmaceutical company with strong oncology and biologics pipeline.",
    websiteUrl: "https://www.intaspharma.com",
    aliases: ["Intas", "Intas Pharmaceuticals"],
  },
  {
    name: "Macleods Pharmaceuticals",
    slug: "macleods",
    headquarters: "Mumbai, India",
    foundedYear: 1989,
    marketCapBillion: 1.5,
    globalRank: 16,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "WHO prequalified manufacturer supplying affordable medicines to 100+ countries.",
    websiteUrl: "https://www.macleodspharma.com",
    aliases: ["Macleods", "Macleods Pharma"],
  },
  {
    name: "Emcure Pharmaceuticals",
    slug: "emcure",
    headquarters: "Pune, India",
    foundedYear: 1981,
    marketCapBillion: 2.5,
    globalRank: 14,
    usFdaApproved: true,
    whoPrequalified: false,
    eugmpCompliant: false,
    description:
      "Strong presence in women's health, HIV, oncology, and blood-related therapeutics.",
    websiteUrl: "https://www.emcure.com",
    aliases: ["Emcure", "Emcure Pharma"],
  },
  {
    name: "Abbott India",
    slug: "abbott-india",
    headquarters: "Mumbai, India",
    foundedYear: 1944,
    marketCapBillion: 8.5,
    globalRank: 2,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "Indian subsidiary of Abbott Laboratories, one of the world's leading healthcare companies.",
    websiteUrl: "https://www.abbott.in",
    aliases: ["Abbott", "Abbott India", "Abbott Healthcare", "Abbott Laboratories"],
  },
  {
    name: "GSK India",
    slug: "gsk-india",
    headquarters: "Mumbai, India",
    foundedYear: 1924,
    marketCapBillion: 5.0,
    globalRank: 11,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "Indian arm of GlaxoSmithKline, one of the world's largest pharma and consumer health companies.",
    websiteUrl: "https://www.gsk.com/en-in",
    aliases: ["GSK", "GlaxoSmithKline", "GSK India", "Glaxo"],
  },
  {
    name: "Hetero Labs",
    slug: "hetero",
    headquarters: "Hyderabad, India",
    foundedYear: 1993,
    marketCapBillion: 2.0,
    globalRank: 15,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "World's largest producer of antiretroviral drugs for HIV/AIDS treatment.",
    websiteUrl: "https://www.heterohealthcare.com",
    aliases: ["Hetero", "Hetero Labs", "Hetero Healthcare"],
  },

  // ─── STANDARD TIER (40-64) ─────────────────────────────────
  {
    name: "Micro Labs Ltd",
    slug: "micro-labs",
    headquarters: "Bangalore, India",
    foundedYear: 1973,
    marketCapBillion: 1.0,
    globalRank: 20,
    usFdaApproved: false,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "Known for the Dolo brand, one of India's largest paracetamol manufacturers.",
    websiteUrl: "https://www.microlabs.in",
    aliases: ["Micro Labs", "Micro Labs Ltd"],
  },
  {
    name: "Aristo Pharmaceuticals",
    slug: "aristo",
    headquarters: "Mumbai, India",
    foundedYear: 1986,
    marketCapBillion: 0.8,
    globalRank: 22,
    usFdaApproved: false,
    whoPrequalified: false,
    eugmpCompliant: false,
    description:
      "Major Indian pharma company with a strong domestic presence in anti-infective, cardiac, and diabetic segments.",
    websiteUrl: "https://www.aristopharma.com",
    aliases: ["Aristo", "Aristo Pharma", "Aristo Pharmaceuticals"],
  },
  {
    name: "USV Private Limited",
    slug: "usv",
    headquarters: "Mumbai, India",
    foundedYear: 1961,
    marketCapBillion: 1.2,
    globalRank: 18,
    usFdaApproved: false,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "Leading player in diabetes and cardiovascular therapy in India.",
    websiteUrl: "https://www.usvindia.com",
    aliases: ["USV", "USV Private Limited", "USV Ltd"],
  },
  {
    name: "Sanofi India",
    slug: "sanofi-india",
    headquarters: "Mumbai, India",
    foundedYear: 1956,
    marketCapBillion: 3.0,
    globalRank: 13,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "Indian subsidiary of the global pharma giant, strong in diabetes care and vaccines.",
    websiteUrl: "https://www.sanofi.in",
    aliases: ["Sanofi", "Sanofi India", "Sanofi-Aventis"],
  },
  {
    name: "Novartis India",
    slug: "novartis-india",
    headquarters: "Mumbai, India",
    foundedYear: 1947,
    marketCapBillion: 2.0,
    globalRank: 17,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "Indian subsidiary of Novartis, focused on innovative and generic medicines.",
    websiteUrl: "https://www.novartis.com/in-en",
    aliases: ["Novartis", "Novartis India"],
  },
  {
    name: "Ipca Laboratories",
    slug: "ipca",
    headquarters: "Mumbai, India",
    foundedYear: 1949,
    marketCapBillion: 3.0,
    globalRank: 19,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "Global leader in antimalarial drugs, exporting to 120+ countries.",
    websiteUrl: "https://www.ipcalabs.com",
    aliases: ["Ipca", "Ipca Labs", "IPCA Laboratories"],
  },
  {
    name: "Ajanta Pharma",
    slug: "ajanta-pharma",
    headquarters: "Mumbai, India",
    foundedYear: 1973,
    marketCapBillion: 3.0,
    globalRank: 21,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "Specialty pharma company focused on branded generics in emerging markets.",
    websiteUrl: "https://www.ajantapharma.com",
    aliases: ["Ajanta", "Ajanta Pharma"],
  },
  {
    name: "Pfizer India",
    slug: "pfizer-india",
    headquarters: "Mumbai, India",
    foundedYear: 1950,
    marketCapBillion: 4.0,
    globalRank: 23,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "Indian subsidiary of the world's leading biopharmaceutical company.",
    websiteUrl: "https://www.pfizer.co.in",
    aliases: ["Pfizer", "Pfizer India", "Pfizer Ltd"],
  },
  {
    name: "Biocon Ltd",
    slug: "biocon",
    headquarters: "Bangalore, India",
    foundedYear: 1978,
    marketCapBillion: 5.0,
    globalRank: 24,
    usFdaApproved: true,
    whoPrequalified: true,
    eugmpCompliant: true,
    description:
      "India's premier biopharmaceutical company specializing in biosimilars and biologics.",
    websiteUrl: "https://www.biocon.com",
    aliases: ["Biocon", "Biocon Ltd", "Biocon Biologics"],
  },
  {
    name: "FDC Limited",
    slug: "fdc",
    headquarters: "Mumbai, India",
    foundedYear: 1936,
    marketCapBillion: 0.5,
    globalRank: 30,
    usFdaApproved: false,
    whoPrequalified: false,
    eugmpCompliant: false,
    description:
      "Known for Electral ORS and Enerzal, a pioneer in oral rehydration solutions.",
    websiteUrl: "https://www.fdcindia.com",
    aliases: ["FDC", "FDC Limited", "FDC Ltd"],
  },
  {
    name: "Meyer Organics",
    slug: "meyer-organics",
    headquarters: "Mumbai, India",
    foundedYear: 1986,
    marketCapBillion: 0.3,
    globalRank: 35,
    usFdaApproved: false,
    whoPrequalified: false,
    eugmpCompliant: false,
    description:
      "Known for Shelcal brand, one of India's most prescribed calcium supplements.",
    websiteUrl: "https://www.meyerorganics.com",
    aliases: ["Meyer Organics", "Meyer"],
  },
  {
    name: "Franco-Indian Pharmaceuticals",
    slug: "franco-indian",
    headquarters: "Mumbai, India",
    foundedYear: 1947,
    marketCapBillion: 0.2,
    globalRank: 40,
    usFdaApproved: false,
    whoPrequalified: false,
    eugmpCompliant: false,
    description:
      "Legacy pharma company known for popular brands in analgesics and anti-infectives.",
    websiteUrl: "https://www.franco-indian.com",
    aliases: ["Franco-Indian", "Franco Indian"],
  },
  {
    name: "Wockhardt Ltd",
    slug: "wockhardt",
    headquarters: "Mumbai, India",
    foundedYear: 1960,
    marketCapBillion: 1.5,
    globalRank: 25,
    usFdaApproved: true,
    whoPrequalified: false,
    eugmpCompliant: false,
    description:
      "Global pharmaceutical and biotechnology company with a focus on anti-infectives.",
    websiteUrl: "https://www.wockhardt.com",
    aliases: ["Wockhardt", "Wockhardt Ltd"],
  },

  // ─── GOVERNMENT SCHEME ──────────────────────────────────────
  {
    name: "Jan Aushadhi",
    slug: "jan-aushadhi",
    headquarters: "New Delhi, India",
    foundedYear: 2008,
    marketCapBillion: undefined,
    globalRank: undefined,
    usFdaApproved: false,
    whoPrequalified: true,
    eugmpCompliant: false,
    description:
      "Indian Government's Pradhan Mantri Bhartiya Janaushadhi Pariyojana providing quality generic medicines at affordable prices through 10,000+ outlets.",
    websiteUrl: "https://janaushadhi.gov.in",
    aliases: ["Jan Aushadhi", "JanAushadhi", "PMBJP", "Pradhan Mantri Jan Aushadhi"],
  },
];
