// Sample data for development and demo purposes
// In production, this comes from scraping 1mg, PharmEasy, Netmeds, etc.

export const sampleDrugs = [
  {
    name: "Dolo 650",
    genericName: "Paracetamol",
    brandName: "Dolo 650",
    manufacturer: "Micro Labs Ltd",
    composition: "Paracetamol 650mg",
    category: "Pain Relief",
    dosageForm: "Tablet",
    packSize: "15 tablets",
    prescriptionReq: false,
    isGeneric: false,
    whoCertified: true,
    description: "Used for fever and mild to moderate pain relief",
    uses: "Fever, Headache, Body ache, Toothache",
    sideEffects: "Nausea, Allergic reactions (rare)",
    prices: [
      { source: "1mg", mrp: 33.62, sellingPrice: 30.26, inStock: true },
      { source: "PharmEasy", mrp: 33.62, sellingPrice: 28.58, inStock: true },
      { source: "Apollo", mrp: 33.62, sellingPrice: 31.00, inStock: true },
      { source: "Netmeds", mrp: 33.62, sellingPrice: 29.20, inStock: true },
    ],
  },
  {
    name: "Paracetamol 650mg (Generic)",
    genericName: "Paracetamol",
    brandName: null,
    manufacturer: "Jan Aushadhi",
    composition: "Paracetamol 650mg",
    category: "Pain Relief",
    dosageForm: "Tablet",
    packSize: "10 tablets",
    prescriptionReq: false,
    isGeneric: true,
    whoCertified: true,
    description: "Generic paracetamol for fever and pain relief",
    uses: "Fever, Headache, Body ache, Toothache",
    sideEffects: "Nausea, Allergic reactions (rare)",
    prices: [
      { source: "JanAushadhi", mrp: 6.00, sellingPrice: 6.00, inStock: true },
      { source: "1mg", mrp: 10.50, sellingPrice: 9.45, inStock: true },
    ],
  },
  {
    name: "Azithral 500",
    genericName: "Azithromycin",
    brandName: "Azithral 500",
    manufacturer: "Alembic Pharmaceuticals",
    composition: "Azithromycin 500mg",
    category: "Antibiotics",
    dosageForm: "Tablet",
    packSize: "5 tablets",
    prescriptionReq: true,
    isGeneric: false,
    whoCertified: true,
    description: "Antibiotic used to treat bacterial infections",
    uses: "Respiratory infections, Ear infections, Skin infections",
    sideEffects: "Diarrhea, Nausea, Abdominal pain",
    prices: [
      { source: "1mg", mrp: 127.90, sellingPrice: 108.72, inStock: true },
      { source: "PharmEasy", mrp: 127.90, sellingPrice: 105.50, inStock: true },
      { source: "Apollo", mrp: 127.90, sellingPrice: 115.11, inStock: true },
    ],
  },
  {
    name: "Azithromycin 500mg (Generic)",
    genericName: "Azithromycin",
    brandName: null,
    manufacturer: "Cipla Ltd",
    composition: "Azithromycin 500mg",
    category: "Antibiotics",
    dosageForm: "Tablet",
    packSize: "5 tablets",
    prescriptionReq: true,
    isGeneric: true,
    whoCertified: true,
    description: "Generic azithromycin antibiotic",
    uses: "Respiratory infections, Ear infections, Skin infections",
    sideEffects: "Diarrhea, Nausea, Abdominal pain",
    prices: [
      { source: "JanAushadhi", mrp: 22.85, sellingPrice: 22.85, inStock: true },
      { source: "1mg", mrp: 45.00, sellingPrice: 38.25, inStock: true },
    ],
  },
  {
    name: "Pan 40",
    genericName: "Pantoprazole",
    brandName: "Pan 40",
    manufacturer: "Alkem Laboratories",
    composition: "Pantoprazole 40mg",
    category: "Gastro",
    dosageForm: "Tablet",
    packSize: "15 tablets",
    prescriptionReq: true,
    isGeneric: false,
    whoCertified: true,
    description: "Proton pump inhibitor for acid reflux and ulcers",
    uses: "Acidity, GERD, Stomach ulcers",
    sideEffects: "Headache, Diarrhea, Flatulence",
    prices: [
      { source: "1mg", mrp: 145.50, sellingPrice: 123.68, inStock: true },
      { source: "PharmEasy", mrp: 145.50, sellingPrice: 118.00, inStock: true },
      { source: "Netmeds", mrp: 145.50, sellingPrice: 120.00, inStock: true },
    ],
  },
  {
    name: "Pantoprazole 40mg (Generic)",
    genericName: "Pantoprazole",
    brandName: null,
    manufacturer: "Jan Aushadhi",
    composition: "Pantoprazole 40mg",
    category: "Gastro",
    dosageForm: "Tablet",
    packSize: "10 tablets",
    prescriptionReq: true,
    isGeneric: true,
    whoCertified: true,
    description: "Generic pantoprazole for acidity and ulcers",
    uses: "Acidity, GERD, Stomach ulcers",
    sideEffects: "Headache, Diarrhea, Flatulence",
    prices: [
      { source: "JanAushadhi", mrp: 14.40, sellingPrice: 14.40, inStock: true },
      { source: "1mg", mrp: 30.00, sellingPrice: 25.50, inStock: true },
    ],
  },
  {
    name: "Crocin Advance",
    genericName: "Paracetamol",
    brandName: "Crocin Advance",
    manufacturer: "GSK",
    composition: "Paracetamol 500mg",
    category: "Pain Relief",
    dosageForm: "Tablet",
    packSize: "20 tablets",
    prescriptionReq: false,
    isGeneric: false,
    whoCertified: true,
    description: "Fast-acting pain and fever relief",
    uses: "Fever, Headache, Cold, Body ache",
    sideEffects: "Nausea, Skin rash (rare)",
    prices: [
      { source: "1mg", mrp: 43.00, sellingPrice: 38.70, inStock: true },
      { source: "PharmEasy", mrp: 43.00, sellingPrice: 36.55, inStock: true },
      { source: "Apollo", mrp: 43.00, sellingPrice: 39.50, inStock: true },
    ],
  },
  {
    name: "Metformin 500mg (Generic)",
    genericName: "Metformin",
    brandName: null,
    manufacturer: "USV Pvt Ltd",
    composition: "Metformin 500mg",
    category: "Diabetes",
    dosageForm: "Tablet",
    packSize: "20 tablets",
    prescriptionReq: true,
    isGeneric: true,
    whoCertified: true,
    description: "First-line medication for type 2 diabetes",
    uses: "Type 2 Diabetes, PCOS",
    sideEffects: "Nausea, Diarrhea, Metallic taste",
    prices: [
      { source: "JanAushadhi", mrp: 11.00, sellingPrice: 11.00, inStock: true },
      { source: "1mg", mrp: 25.40, sellingPrice: 21.59, inStock: true },
    ],
  },
  {
    name: "Glycomet 500",
    genericName: "Metformin",
    brandName: "Glycomet 500",
    manufacturer: "USV Pvt Ltd",
    composition: "Metformin 500mg",
    category: "Diabetes",
    dosageForm: "Tablet",
    packSize: "20 tablets",
    prescriptionReq: true,
    isGeneric: false,
    whoCertified: true,
    description: "Branded metformin for blood sugar control",
    uses: "Type 2 Diabetes, PCOS",
    sideEffects: "Nausea, Diarrhea, Metallic taste",
    prices: [
      { source: "1mg", mrp: 31.00, sellingPrice: 26.35, inStock: true },
      { source: "PharmEasy", mrp: 31.00, sellingPrice: 25.00, inStock: true },
      { source: "Apollo", mrp: 31.00, sellingPrice: 28.50, inStock: true },
    ],
  },
  {
    name: "Amlodipine 5mg (Generic)",
    genericName: "Amlodipine",
    brandName: null,
    manufacturer: "Cipla Ltd",
    composition: "Amlodipine 5mg",
    category: "Heart & BP",
    dosageForm: "Tablet",
    packSize: "14 tablets",
    prescriptionReq: true,
    isGeneric: true,
    whoCertified: true,
    description: "Calcium channel blocker for high blood pressure",
    uses: "Hypertension, Angina",
    sideEffects: "Swelling in ankles, Dizziness, Flushing",
    prices: [
      { source: "JanAushadhi", mrp: 3.36, sellingPrice: 3.36, inStock: true },
      { source: "1mg", mrp: 12.00, sellingPrice: 10.20, inStock: true },
    ],
  },
  {
    name: "Stamlo 5",
    genericName: "Amlodipine",
    brandName: "Stamlo 5",
    manufacturer: "Dr. Reddy's",
    composition: "Amlodipine 5mg",
    category: "Heart & BP",
    dosageForm: "Tablet",
    packSize: "14 tablets",
    prescriptionReq: true,
    isGeneric: false,
    whoCertified: true,
    description: "Branded amlodipine for blood pressure control",
    uses: "Hypertension, Angina",
    sideEffects: "Swelling in ankles, Dizziness, Flushing",
    prices: [
      { source: "1mg", mrp: 56.50, sellingPrice: 48.03, inStock: true },
      { source: "PharmEasy", mrp: 56.50, sellingPrice: 46.00, inStock: true },
      { source: "Apollo", mrp: 56.50, sellingPrice: 50.00, inStock: true },
    ],
  },
];

export const sampleProcedures = [
  {
    name: "Knee Replacement Surgery",
    slug: "knee-replacement",
    category: "Orthopedics",
    description: "Total knee replacement surgery to relieve pain and restore function in severely diseased knee joints.",
    duration: "2-3 hours",
    recoveryTime: "6-8 weeks",
    anesthesia: "General/Spinal",
    prices: [
      { hospitalName: "Apollo Hospital", city: "Delhi", minPrice: 150000, maxPrice: 350000, avgPrice: 250000, includesStay: true, accreditation: "NABH", rating: 4.5 },
      { hospitalName: "Fortis Hospital", city: "Mumbai", minPrice: 180000, maxPrice: 400000, avgPrice: 280000, includesStay: true, accreditation: "NABH", rating: 4.3 },
      { hospitalName: "Government Hospital", city: "Delhi", minPrice: 25000, maxPrice: 60000, avgPrice: 40000, includesStay: true, accreditation: null, rating: 3.5 },
      { hospitalName: "Max Hospital", city: "Delhi", minPrice: 200000, maxPrice: 380000, avgPrice: 290000, includesStay: true, accreditation: "NABH", rating: 4.4 },
    ],
  },
  {
    name: "Cataract Surgery",
    slug: "cataract-surgery",
    category: "Ophthalmology",
    description: "Surgical removal of clouded lens and replacement with artificial intraocular lens.",
    duration: "30-45 minutes",
    recoveryTime: "1-2 weeks",
    anesthesia: "Local",
    prices: [
      { hospitalName: "Eye Care Centre", city: "Delhi", minPrice: 15000, maxPrice: 50000, avgPrice: 30000, includesStay: false, accreditation: "NABH", rating: 4.6 },
      { hospitalName: "Shankar Netralaya", city: "Chennai", minPrice: 20000, maxPrice: 60000, avgPrice: 35000, includesStay: false, accreditation: "NABH", rating: 4.8 },
      { hospitalName: "Government Eye Hospital", city: "Mumbai", minPrice: 5000, maxPrice: 15000, avgPrice: 10000, includesStay: false, accreditation: null, rating: 3.8 },
    ],
  },
  {
    name: "Appendectomy",
    slug: "appendectomy",
    category: "General Surgery",
    description: "Laparoscopic or open surgical removal of the appendix.",
    duration: "1-2 hours",
    recoveryTime: "2-4 weeks",
    anesthesia: "General",
    prices: [
      { hospitalName: "Apollo Hospital", city: "Bangalore", minPrice: 60000, maxPrice: 150000, avgPrice: 100000, includesStay: true, accreditation: "NABH", rating: 4.5 },
      { hospitalName: "Narayana Health", city: "Bangalore", minPrice: 45000, maxPrice: 90000, avgPrice: 65000, includesStay: true, accreditation: "NABH", rating: 4.6 },
      { hospitalName: "Government Hospital", city: "Bangalore", minPrice: 10000, maxPrice: 30000, avgPrice: 20000, includesStay: true, accreditation: null, rating: 3.4 },
    ],
  },
  {
    name: "Hernia Repair",
    slug: "hernia-repair",
    category: "General Surgery",
    description: "Laparoscopic mesh repair surgery for inguinal or umbilical hernia.",
    duration: "1-2 hours",
    recoveryTime: "2-3 weeks",
    anesthesia: "General",
    prices: [
      { hospitalName: "Fortis Hospital", city: "Delhi", minPrice: 50000, maxPrice: 120000, avgPrice: 80000, includesStay: true, accreditation: "NABH", rating: 4.3 },
      { hospitalName: "Max Hospital", city: "Delhi", minPrice: 55000, maxPrice: 130000, avgPrice: 85000, includesStay: true, accreditation: "NABH", rating: 4.4 },
      { hospitalName: "Govt. Safdarjung Hospital", city: "Delhi", minPrice: 8000, maxPrice: 20000, avgPrice: 12000, includesStay: true, accreditation: null, rating: 3.3 },
    ],
  },
  {
    name: "Coronary Bypass (CABG)",
    slug: "coronary-bypass",
    category: "Cardiology",
    description: "Open-heart surgery to improve blood flow to the heart.",
    duration: "4-6 hours",
    recoveryTime: "8-12 weeks",
    anesthesia: "General",
    prices: [
      { hospitalName: "AIIMS", city: "Delhi", minPrice: 100000, maxPrice: 200000, avgPrice: 150000, includesStay: true, accreditation: "NABH", rating: 4.7 },
      { hospitalName: "Medanta", city: "Gurgaon", minPrice: 250000, maxPrice: 500000, avgPrice: 375000, includesStay: true, accreditation: "NABH", rating: 4.6 },
      { hospitalName: "Narayana Health", city: "Bangalore", minPrice: 150000, maxPrice: 300000, avgPrice: 225000, includesStay: true, accreditation: "NABH", rating: 4.7 },
    ],
  },
];

export const sampleDiagnostics = [
  {
    name: "Complete Blood Count (CBC)",
    slug: "cbc-test",
    category: "Blood Test",
    type: "Blood",
    description: "Measures different components of blood including RBC, WBC, hemoglobin, platelets.",
    preparation: "No special preparation needed",
    reportTime: "Same day",
    homeCollection: true,
    prices: [
      { labName: "Dr Lal PathLabs", city: "Delhi", mrp: 450, sellingPrice: 320, homeCollection: true, accreditation: "NABL" },
      { labName: "SRL Diagnostics", city: "Delhi", mrp: 400, sellingPrice: 280, homeCollection: true, accreditation: "NABL" },
      { labName: "Thyrocare", city: "Pan India", mrp: 350, sellingPrice: 200, homeCollection: true, accreditation: "NABL" },
      { labName: "Government Lab", city: "Delhi", mrp: 100, sellingPrice: 100, homeCollection: false, accreditation: null },
    ],
  },
  {
    name: "Thyroid Profile (T3, T4, TSH)",
    slug: "thyroid-profile",
    category: "Blood Test",
    type: "Blood",
    description: "Measures thyroid hormones to check thyroid function.",
    preparation: "No special preparation. Morning sample preferred.",
    reportTime: "Same day",
    homeCollection: true,
    prices: [
      { labName: "Dr Lal PathLabs", city: "Delhi", mrp: 720, sellingPrice: 500, homeCollection: true, accreditation: "NABL" },
      { labName: "Thyrocare", city: "Pan India", mrp: 500, sellingPrice: 300, homeCollection: true, accreditation: "NABL" },
      { labName: "Metropolis", city: "Mumbai", mrp: 800, sellingPrice: 550, homeCollection: true, accreditation: "NABL" },
    ],
  },
  {
    name: "HbA1c (Glycated Hemoglobin)",
    slug: "hba1c-test",
    category: "Blood Test",
    type: "Blood",
    description: "Measures average blood sugar over the past 2-3 months. Key test for diabetes management.",
    preparation: "No fasting required",
    reportTime: "Same day",
    homeCollection: true,
    prices: [
      { labName: "Dr Lal PathLabs", city: "Delhi", mrp: 550, sellingPrice: 385, homeCollection: true, accreditation: "NABL" },
      { labName: "SRL Diagnostics", city: "Mumbai", mrp: 600, sellingPrice: 420, homeCollection: true, accreditation: "NABL" },
      { labName: "Thyrocare", city: "Pan India", mrp: 400, sellingPrice: 250, homeCollection: true, accreditation: "NABL" },
    ],
  },
  {
    name: "MRI Brain",
    slug: "mri-brain",
    category: "Imaging",
    type: "MRI",
    description: "Detailed imaging of brain structures using magnetic resonance.",
    preparation: "Remove all metal objects. Inform about any implants.",
    reportTime: "24-48 hours",
    homeCollection: false,
    prices: [
      { labName: "Apollo Diagnostics", city: "Delhi", mrp: 8000, sellingPrice: 6500, homeCollection: false, accreditation: "NABL" },
      { labName: "Max Lab", city: "Delhi", mrp: 9000, sellingPrice: 7200, homeCollection: false, accreditation: "NABL" },
      { labName: "Government Hospital", city: "Delhi", mrp: 2500, sellingPrice: 2500, homeCollection: false, accreditation: null },
    ],
  },
  {
    name: "CT Scan Chest",
    slug: "ct-scan-chest",
    category: "Imaging",
    type: "CT Scan",
    description: "Cross-sectional imaging of chest/lungs using X-ray technology.",
    preparation: "May require fasting. Inform about allergies if contrast is used.",
    reportTime: "24 hours",
    homeCollection: false,
    prices: [
      { labName: "Apollo Diagnostics", city: "Delhi", mrp: 5500, sellingPrice: 4400, homeCollection: false, accreditation: "NABL" },
      { labName: "Fortis Lab", city: "Mumbai", mrp: 6000, sellingPrice: 5000, homeCollection: false, accreditation: "NABL" },
      { labName: "Government Hospital", city: "Delhi", mrp: 1500, sellingPrice: 1500, homeCollection: false, accreditation: null },
    ],
  },
  {
    name: "Lipid Profile",
    slug: "lipid-profile",
    category: "Blood Test",
    type: "Blood",
    description: "Measures cholesterol levels including total cholesterol, HDL, LDL, and triglycerides.",
    preparation: "Fasting for 10-12 hours",
    reportTime: "Same day",
    homeCollection: true,
    prices: [
      { labName: "Dr Lal PathLabs", city: "Delhi", mrp: 600, sellingPrice: 420, homeCollection: true, accreditation: "NABL" },
      { labName: "Thyrocare", city: "Pan India", mrp: 450, sellingPrice: 250, homeCollection: true, accreditation: "NABL" },
      { labName: "SRL Diagnostics", city: "Mumbai", mrp: 550, sellingPrice: 385, homeCollection: true, accreditation: "NABL" },
    ],
  },
];

export const drugCategories = [
  "Pain Relief",
  "Antibiotics",
  "Gastro",
  "Diabetes",
  "Heart & BP",
  "Vitamins",
  "Skin Care",
  "Respiratory",
  "Mental Health",
  "Thyroid",
];

export const procedureCategories = [
  "Orthopedics",
  "Ophthalmology",
  "General Surgery",
  "Cardiology",
  "Urology",
  "Gynecology",
  "ENT",
  "Neurology",
  "Cosmetic",
  "Dental",
];

export const diagnosticCategories = [
  "Blood Test",
  "Imaging",
  "Pathology",
  "Cardiac",
  "Allergy",
  "Hormone",
];
